# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Publications"
  url = "/publication"
  weight = 10

[[main]]
  name = "Projects"
  url = "/post"
  weight = 20 

#[[main]]
#  name = "Projects"
#  url = "/project"
#  weight = 20

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
    name = "Resume"
    url = "files/Wei_Guo_resume.pdf"
    weight = 30
    
[[main]]
  name = "About / Contact"
  url = "/contact"
  weight = 40